### ISSUE TITLE
Need Whatsapp Web feature!

### ISSUE THREAD

**Issue by yesbhautik** [father-bot/WhatsApp-ChatGPT-bot#1]
You can use whatsappweb,js or baileys libraries

**Comment by Hand-of-Doom** [comment]
Sorry for a long wait, it took a while to start working on this. Your suggestion has been approved and the development is started (i'll close this issue once it's done)

**Comment by yesbhautik** [comment]
baileys has more features and good documentation.

**Comment by Hand-of-Doom** [comment]
I think baileys is better (at least because of type hints), it's porting to baileys right now on this [branch](https://github.com/father-bot/WhatsApp-ChatGPT-bot/tree/baileys)

**Comment by yesbhautik** [comment]
looks like [baileys branch](https://github.com/father-bot/WhatsApp-ChatGPT-bot/tree/baileys) come with too many bugs.

**Comment by Hand-of-Doom** [comment]
> looks like [baileys branch](https://github.com/father-bot/WhatsApp-ChatGPT-bot/tree/baileys) come with too many bugs.

It wasn't done 3 days ago (on 4th of march I suggest)

Today it's over, feel free to left any new issues if it has some bugs or new improvements are suggested

I close this issue, thanks

**Comment by yesbhautik** [comment]
Source code not updated yet.

**Comment by Hand-of-Doom** [comment]
> Source code not updated yet.

What do you mean by that?
Does it work on your machine?

**Comment by yesbhautik** [comment]
> > Source code not updated yet.
> 
> What do you mean by that? Does it work on your machine?

not it is not

**Comment by Hand-of-Doom** [comment]
> not it is not

Can you list all the problems you have faced?
It's 100% work on my machine
